apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: notebook-home
      containers:
      - name: notebook
        image: jupyter/tensorflow-notebook
        ports:
        - containerPort: 8888
        - containerPort: 6006
        volumeMounts:
        - mountPath: "/home/jovyan"
          name: home
