apiVersion: v1
kind: Service
metadata:
  name: notebook
spec:
  type: LoadBalancer
  selector:
    app: notebook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
    name: http
  - protocol: TCP
    port: 6006
    targetPort: 6006
    name: tensorboard
