apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /nfs-server-provisioner
  claimRef:
    namespace: nfs-server
    name: data-nfs-server-provisioner-0
